doctron:
  maxConvertWorker: 50
  env: prod
  retry: true
  maxConvertQueue: 60
  convertTimeout: 10
  uploader: alioss
  domain: 0.0.0.0:8090
  TLSCertFile: certfile
  TLSKeyFile: keyfile
  user:
    - username: doctron
      password: lampnick
oss:
  endpoint: 
  accessKeyId: 
  accessKeySecret: 
  bucketName: 
  privateServerDomain: 

